Algoritmo "Área de um retângulo"
// Disciplina  : Aplicações Informáticas B
// Professor   : Daniel Edgar Soares 
// Descrição   : Fornece a área de um retângulo, dados pelo utilizador o comprimento e largura.
// Autor(a)    : Marcos Bernardo da Silva Lobo
// Data atual  : 25/02/2024

Var
COMP, LARG, AREA: real

Inicio
      Leia(COMP)
      Leia(LARG)
      AREA<-COMP*LARG
      Escreva(AREA)
Fimalgoritmo