Algoritmo "Média de dois números"
// Disciplina  : Aplicações Informáticas B
// Professor   : Daniel Edgar Soares
// Descrição   : Fornece a média de dois números dados pelo utilizador.
// Autor(a)    : Marcos Bernardo da Silva Lobo
// Data atual  : 23/02/2024

Var
NUM1, NUM2, MEDIA:real

Inicio
      Leia(NUM1)
      Leia(NUM2)
      MEDIA<-(NUM1+NUM2)/2
      Escreva(MEDIA)
Fimalgoritmo