Algoritmo "Quadrado de um número"
// Disciplina  : Aplicações Informáticas B
// Professor   : Daniel Edgar Soares
// Descrição   : Fornece o quadrado do número dado pelo utilizador.
// Autor(a)    : Marcos Bernardo da Silva Lobo
// Data atual  : 23/02/2024

Var
NUM1, QUADRADO:real

Inicio
      Leia(NUM1)
      QUADRADO<-NUM1*NUM1
      QUADRADO<-NUM1^2
      Escreva(QUADRADO)
Fimalgoritmo